// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgqlfdhnlldruwknvbhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncWxmZGhubGxkcnV3a252YmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MDAxODEsImV4cCI6MjA1MTA3NjE4MX0.NLVFbDXjm_NlxPrn3Ed40w8paBFo4BlWv-OBDqWSryE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);